language: csharp
os:
  - osx
  - linux
sudo: required
dist: trusty
dotnet: 1.0.0-preview2-003121
mono: none
env:
  global:
    - CLI_VERSION=latest
    - ASPNETCORE_ENVIRONMENT="tests"
    - DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
    - PATH="$DOTNET_INSTALL_DIR:$PATH"
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
  - ./build.sh --verbosity diagnostic

cache:
  directories:
    - .packages
