language: csharp
os:
  - osx
  - linux
sudo: required
dist: trusty
dotnet: 1.0.0-preview2-003121
mono:  
  - 4.2.3
env:
  global:
    - CLI_VERSION=latest
    - ASPNETCORE_ENVIRONMENT="tests"
    - DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
    - PATH="$DOTNET_INSTALL_DIR:$PATH"
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

script:
  - ./build.sh --verbosity diagnostic

cache:
  directories:
    - .packages
    - tools/Addins
